#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
if [ ! -f $SCRIPT_DIR/.project/TypeCLI/a.out ]; then
  SAVEDIR=$PWD
  cd $SCRIPT_DIR/.project/TypeCLI
  make a.out >/dev/null
  cd $SAVEDIR
fi


function run() {
  if ! $SCRIPT_DIR/.project/TypeCLI/a.out $@ 2>/dev/null ; then
    SAVEDIR=$PWD
    cd $SCRIPT_DIR/.project/TypeCLI
    make clean >/dev/null
    make >/dev/null
    cd $SAVEDIR
    run
  fi
}

run
